project:
  type: website

manuscript:
  resources:
    - data/Sample_Clouclip.csv
    - data/01_VEET_L.csv.zip
    - data/02_VEET_L.csv.zip
    - data/VEET_calibration_matrix.csv

website:
  title: "Analysis of human visual experience data"
  site-url: https://tscnlab.github.io/ZaunerEtAl_JVis_2026/
  repo-url: https://github.com/tscnlab/ZaunerEtAl_JVis_2026
  issue-url: https://github.com/tscnlab/ZaunerEtAl_JVis_2026/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Manuscript
      - href: supplement.qmd
        text: Supplement
    right:
      - icon: github
        href: https://github.com/tscnlab/ZaunerEtAl_JVis_2026
        aria-label: Quarto GitHub


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    link-external-newwindow: true
    toc: true
    # comments:
    #   hypothesis: true
    format:
    code-link: true
    code-line-numbers: true
    toc-location: left
    toc-depth: 3
    toc-expand: 2
  # typst:
  #   toc: true
  #   toc-depth: 3
  #   number-sections: true
  #   papersize: a4
  #   fig-format: png
  #   fig-dpi: 600
  #   fig-height: 3.45
format-links:
  - html
  # - format: typst
  #   text: PDF
  #   icon: file-pdf


date: last-modified

language:
  title-block-published: "Last modified:"

execute:
  warning: false
  error: false
  echo: true
  freeze: auto
